management:
  endpoints:
    web:
      exposure:
         include: "*"

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: SA
    password: 12345678
    data: classpath:data.sql
    schema: classpath:schema.sql
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
